name: flutter_voice_chat
description: A voice chat application that transcribes speech to text.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  record: ^5.0.4
  permission_handler: ^11.0.1
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.1
  logging: ^1.2.0
  app_settings: ^5.1.1
  universal_html: ^2.2.4
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
